# Site settings
title: Francisco Caballero
email: fjcero@gmail.com

description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fjcero.github.io" # the base hostname & protocol for your site
twitter_username: fjcero
github_username:  fjcero

# Build settings
markdown: kramdown
