# Site settings
title: fcaballero
header-img: img/home-bg.jpg
email: fjcero@gmail.com
description: >
  This is my personal page to put stuff I found and ideas to do.
baseurl: ""
url: "http://fjcero.github.io"
twitter_username:  fjcero
github_username:   fjcero
facebook_username: fjcero

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
